### ISSUE TITLE
Web Proxy Support

### ISSUE THREAD

**Issue by dkfi** [Asana/java-asana#76]
I'm currently unable to get the Personal Access Token example to run successfully because web traffic is only allowed through our corporate proxy. The following stack trace shows that java-asana uses com.google.api.client.http.HttpRequest to initiate the HTTP request:

```
== Example using a personal access token:
Exception in thread "main" java.net.ConnectException: Connessione rifiutata (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:93)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:972)
	at com.asana.Client.request(Client.java:194)
	at com.asana.requests.ItemRequest.executeRaw(ItemRequest.java:38)
	at com.asana.requests.ItemRequest.execute(ItemRequest.java:27)
	at it.hitechsanita.portasana.Portasana.main(Portasana.java:29)
```
The library is ignoring the HTTP_PROXY and HTTPS_PROXY environment variables and I see no instructions on how to get this to work in README. Is proxy support actually missing and in the project roadmap somewhere?

**Comment by praecipula** [comment]
I believe that Google's library will delegate under the hood to Java's included networking libraries (https://developers.google.com/api-client-library/java/google-http-java-client/transport), so can you try looking into `System.setProperty` with `http.proxyHost` and `http.proxyPort`? https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html I have to admit I've never tried this, but that's the next thing I'd give a try to see if that works.

**Comment by dkfi** [comment]
Thanks a lot @praecipula ! That worked perfectly. Traffic was https so I solved it by providing the https.proxyHost and https.proxyPort java properties.
